name: types

on:
  pull_request:
    types:
      - opened
    branches:
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run tests, i.e. compile everything
        run: yarn test
